[package]
name = "factorio-cli"
description = "A command line tool to export prototype definitions from Factorio (http://www.factorio.com)"
version = "0.1.0"

authors = ["Michael Forster <email@michael-forster.de>"]
edition = "2021"
homepage = "http://github.com/MForster/factorio-rust-tools"
repository = "http://github.com/MForster/factorio-rust-tools"
license = "MIT OR Apache-2.0"
keywords = ["gaming", "factorio"]
rust-version = "1.60.0"

[[bin]]
name = "fct"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
factorio-exporter = { version = "0.6.0", path = "../factorio-exporter" }
indoc = "1.0.7"
serde_json = "1.0.87"
serde_yaml = "0.9.14"
tracing = "0.1.37"
